version: '3.8'

services:
  c2-preprocessor:
    build: ./c2_preprocessor
    container_name: c2_preprocessor
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - INFERENCE_URL=http://c3-inference:5002/infer
    volumes:
      - ./c2_preprocessor:/app
    networks:
      - snack-pipeline-net
    depends_on:
      - c3-inference

  c3-inference:
    build: ./c3_inference_core
    container_name: c3_inference_core
    restart: unless-stopped
    ports:
      - "5002:5002"
    environment:
      - VISUALIZER_URL=http://host.docker.internal:5003/visualize
    volumes:
      - ./c3_inference_core:/app
    networks:
      - snack-pipeline-net

networks:
  snack-pipeline-net:
    driver: bridge
